### ISSUE TITLE
Eclipse runs do not work

### ISSUE THREAD

**Issue by CreativeMD** [neoforged/MDK#28]
Hey, imported the template into eclipse and unfortunately the run configurations do not work, because it does not trigger the task prepareRuns from gradle, which means `mods.toml` and `pack.mcmeta` will not be filled in correctly, causing minecraft to crash on startup.

**Comment by Technici4n** [comment]
You need to use the group not the run.

**Comment by CreativeMD** [comment]
Oh yes ... did not see that. Thanks for pointing this out! Sorry for the trouble.
