### ISSUE TITLE
Build action failing when creating a release

### ISSUE THREAD

**Issue by jwolff52** [neoforged/MDK#39]
I just created the first release for a new mod that I created using the MDK and when I did so the [Build action failed](https://github.com/jwolff52/NotTheGrass/actions/runs/7967085143/job/21749328883), this seems to be a known issue with the checkout action (actions/checkout#1471).

I did some testing and it seems to only be an issue when the checkout is run on a tag (for example during a release) Each of the logs [here](https://github.com/jwolff52/test/actions/runs/7968110909) and [here](https://github.com/jwolff52/test/actions/runs/7976427708/job/21776972969) are run against the same code, the only difference being that the second one is run against a tag during a release. As several comments on the issue above suggests changing `fetch-depth` to `0` solves the issue, though it can apparently [cause slowdowns](https://github.com/actions/checkout/issues/1471#issuecomment-1755560284) for larger projects.

**Comment by Technici4n** [comment]
I don't know about this. One possible fix is to make a github release instead (e.g. https://github.com/AztechMC/Modern-Industrialization/blob/1.20/.github/workflows/release.yml).
