### ISSUE TITLE
Example for delaying reobfuscation until publish does not work.

### ISSUE THREAD

**Issue by noeppi-noeppi** [neoforged/MDK#4]
*Copy of https://github.com/MinecraftForge/MinecraftForge/issues/9605*

**Description of issue:**

The MDK shows the following example on how to delay the reobfuscation of the jar file (by the `reobfJar`) task:
```gradle
tasks.named('publish').configure {
    dependsOn 'reobfJar'
}
```
The `maven-publish` plugin will create a separate task (named `publishMavenJavaPublicationToMavenRepository` by default) for each publication. This task actually published the artifact. The `publish` task itself does nothing, it's purpose is to have all those publishing tasks as dependnecies.

Using the shown example from the MDK, both the `publishMavenJavaPublicationToMavenRepository`and the `reobfJar` task will become dependencies of the `publish` task. When executing `publish`, it can happen, that `publishMavenJavaPublicationToMavenRepository` runs *before* `reobfJar`, publishing a deobfuscated jar file to the maven repository.

The correct way to specify that the the `reobfJar` task should run before the publication, is to use the `builtBy` method of `PublicationArtifact` like this:
```gradle
publishing {
    publications {
        mavenJava(MavenPublication) {
            // All the other configuration of the publication
            artifact(jar) {
                builtBy project.provider { project.tasks.named('reobfJar') }
            }
        }
    }
}
```
I think, the MDK should direct the modder to this approach or at least not show an example that does not work and publishes deobfuscated jars into the maven.

**Comment by Technici4n** [comment]
There is no reobf anymore. :rocket:
