### ISSUE TITLE
issues when gradle

### ISSUE THREAD

**Issue by Ian795** [neoforged/MDK#41]
I haven't met the issues below.

Starting Gradle Daemon...
Gradle Daemon started in 1 s 804 ms

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* Where:
Build file 'C:\Users\m1952\Desktop\originalNeoForged\build.gradle' line: 83

* What went wrong:
A problem occurred evaluating root project 'originalNeoForged'.
> Uncaught exception while processing replacement of dependency net.neoforged:neoforge using handler net.neoforged.gradle.common.extensions.dependency.replacement.DependencyReplacementHandlerImpl_Decorated@62bcc26c: Failed to download the file from: https://piston-meta.mojang.com/mc/game/version_manifest.json to: C:\Users\m1952\.gradle\caches\minecraft\.\launcher_metadata.json

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring root project 'originalNeoForged'.
> Could not find run type client. Available run types: []

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 20s

**Comment by Technici4n** [comment]
> Failed to download the file from: https://piston-meta.mojang.com/mc/game/version_manifest.json to: C:\Users\m1952.gradle\caches\minecraft.\launcher_metadata.json

That's your issue

**Comment by zybzbk** [comment]
Could you please tell me if you've solved this problem?
