### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by lZiMUl** [neoforged/MDK#54]
In this file /src/main/resources/META-INF/neoforge.mods.toml
There are some bugs

The IDE error is due to this [[dependencies.${mod_id}]]
It should be [[dependencies."${mod_id}"]]

Includes 69 lines, 88 lines, 99 lines

**Comment by Spinoscythe** [comment]
that shouldn't cause issues. it just says an issue cause it has to. this shouldn't cause an error in the runtime

**Comment by lZiMUl** [comment]
> 这应该不会引起问题。它只是说一个问题，因为它必须这样做。这不应导致运行时出错

![image](https://github.com/neoforged/MDK/assets/45619879/1aac83ff-b55f-4ade-9279-b3734a0fe456)

Are you sure that's okay?

**Comment by TelepathicGrunt** [comment]
If you build the jar file and open it up, does the neoforge.mods.toml file there have the value replaced properly?

**Comment by lZiMUl** [comment]
> 如果您构建 jar 文件并打开它，那里的 neoforge.mods.toml 文件是否正确替换了值？

I haven't compiled and tested it yet
Because most of my mods are no longer working
At the moment I don't know what to do
I went to the official documentation and didn't give a specific method for the time being


lol :)

**Comment by Shadows-of-Fire** [comment]
We use gradle's `processResources` task to do template expansion in the `neoforge.mods.toml` file so you don't have to duplicate data between `gradle.properties` and `neoforge.mods.toml`.  This means that before the template expansion, the syntax is invalid, but it will be corrected when at build time.

You can see the part of the `build.gradle` responsible for the expansion [here](https://github.com/neoforged/MDK/blob/main/build.gradle#L119).
