### ISSUE TITLE
[Request] Add pack.mcmeta to the ExampleMod code.

### ISSUE THREAD

**Issue by Sinhika** [neoforged/MDK#62]
Please add an example pack.mcmeta to the ExampleMod source code, that shows how to represent split format numbers. I.e, as frequently happens, when the resource pack format version is not the same as the data pack format version.

**Comment by Matyrobbrt** [comment]
The `pack.mcmeta` file is no longer required. When absent NeoForge will create one automatically, compatible with the current resource and data pack version.
