### ISSUE TITLE
Gradle load fail on MacOS

### ISSUE THREAD

**Issue by Ramen5914** [neoforged/MDK#69]
Using the latest version of the MDK, I am getting an error when I try to load the java project on mac.

Execution failed for task ':neoFormRecompile'.
> Could not resolve all files for configuration ':neoGradleInternalUnhandledNeoFormMinecraftDependenciesForneoFormJoined1.20.6-20240429.153634'.
   > Could not find lwjgl-freetype-3.3.3-natives-macos-patch.jar (org.lwjgl:lwjgl-freetype:3.3.3).
     Searched in the following locations:
         https://maven.neoforged.net/releases/org/lwjgl/lwjgl-freetype/3.3.3/lwjgl-freetype-3.3.3-natives-macos-patch.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by Ramen5914** [comment]
I tried to add the maven repository that has the lwjgl-freetype jar but it didn't work.

**Comment by Anonymous2416** [comment]
having the same issue on Mac

**Comment by TelepathicGrunt** [comment]
@Ramen5914 

See if updating NeoGradle works for you. In your build.gradle file, change the neogradle version to this https://projects.neoforged.net/neoforged/neogradle

Then reimport the project or refresh gradle and try again

**Comment by Ramen5914** [comment]
> @Ramen5914
> 
> See if updating NeoGradle works for you. In your build.gradle file, change the neogradle version to this https://projects.neoforged.net/neoforged/neogradle
> 
> Then reimport the project or refresh gradle and try again

That was it, thanks!!! I can make a PR that updates the MDK to the latest version of neoforged and neogradle.

**Comment by Ramen5914** [comment]
@CrypticVerse
Yeah, that's basically the problem, but the solution is just to update NeoGradle and then it is able to find the right artifact.

**Comment by Shadows-of-Fire** [comment]
Versions have been updated to latest for 1.20.6
